name: covid_traking
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.0+2
  get_it: ^7.6.7
  go_router: ^13.2.0
  http: ^1.2.0
  localstorage: ^4.0.1+4
  mobx: ^2.3.0+1
  device_info_plus: ^9.1.2

dev_dependencies:
  build_runner: ^2.4.8
  faker: ^2.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.0+1
  mocktail: ^1.0.3
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/core/constants/user.json
